dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq \
        gstreamer1.0-plugins-bad \
        libgtk-3-dev \
        libjson-glib-dev \
        python3-pip \
        valac

script:
- mkdir build
- meson build
- ninja -C build
